### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by ElMehdiElMellaliMobile** [Xavalon/XamlStyler#179]
26/03/2019 11:55:32 - 	InstalledByMSI     : False
26/03/2019 11:55:32 - 	SupportedFrameworkVersionRange : [4.0,4.5)
26/03/2019 11:55:32 - 
26/03/2019 11:55:32 - 	SignatureState     : Unsigned
26/03/2019 11:55:32 - 	Supported Products : 
26/03/2019 11:55:32 - 		Microsoft.VisualStudio.Pro
26/03/2019 11:55:32 - 			Version : [14.0,15.0)
26/03/2019 11:55:32 - 		Microsoft.VisualStudio.Premium
26/03/2019 11:55:32 - 			Version : [14.0,15.0)
26/03/2019 11:55:32 - 		Microsoft.VisualStudio.Ultimate
26/03/2019 11:55:32 - 			Version : [12.0,14.0)
26/03/2019 11:55:32 - 		Microsoft.VisualStudio.Enterprise
26/03/2019 11:55:32 - 			Version : [14.0,15.0)
26/03/2019 11:55:32 - 		Microsoft.VisualStudio.Community
26/03/2019 11:55:32 - 			Version : [14.0,15.0)
26/03/2019 11:55:32 - 
26/03/2019 11:55:32 - 	References         : 
26/03/2019 11:55:32 - 		-------------------------------------------------------
26/03/2019 11:55:32 - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
26/03/2019 11:55:32 - 		Name         : Visual Studio MPF 12.0
26/03/2019 11:55:32 - 		Version      : [12.0]
26/03/2019 11:55:32 - 		MoreInfoURL  : 
26/03/2019 11:55:32 - 		Nested       : No
26/03/2019 11:55:32 - 
26/03/2019 11:55:32 - Signature Details...
26/03/2019 11:55:32 - 	Extension is not signed.
26/03/2019 11:55:32 - 
26/03/2019 11:55:32 - Searching for applicable products...
26/03/2019 11:55:32 - Found installed product - Global Location
26/03/2019 11:55:32 - Found installed product - ssms
26/03/2019 11:55:32 - Found installed product - Visual Studio Enterprise 2017
26/03/2019 11:55:32 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by NicoVermeir** [comment]
can you give some more information? what version of xaml styler are you installing, what version of visual studio are you running?
