### ISSUE TITLE
rider plugin keep crashing when using external config file

### ISSUE THREAD

**Issue by roubachof** [Xavalon/XamlStyler#340]
JetBrains Rider 2021.1.2
Build #RD-211.7142.19, built on April 22, 2021
Licensed to Jean-Marie Alfonsi
Subscription is active until February 12, 2022.
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
.NET Core 5.0.5

When formatting on save, the plugins crashes sometimes for unknown reason.
Here is the stacktrace reported by rider:

```
java.lang.IndexOutOfBoundsException: Wrong endOffset: 4870; documentLength: 4869
	at com.intellij.openapi.editor.impl.DocumentImpl.assertBounds(DocumentImpl.java:670)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:603)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:597)
	at xavalon.plugins.xamlstyler.rider.XamlStylerComponent$beforeDocumentSaving$1$1.run(XamlStylerComponent.kt:53)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:347)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:182)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:150)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:117)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:347)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:335)
	at xavalon.plugins.xamlstyler.rider.XamlStylerComponent$beforeDocumentSaving$1.invoke(XamlStylerComponent.kt:52)
	at xavalon.plugins.xamlstyler.rider.XamlStylerComponent$beforeDocumentSaving$1.invoke(XamlStylerComponent.kt:18)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseOnce$1.invoke(SourceEx.kt:16)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseOnce$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt:27)
	at com.jetbrains.rd.util.reactive.SourceExKt$adviseUntil$1$1.invoke(SourceEx.kt)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty$WriteOnceSignal.fire(Property.kt:120)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty.setIfEmpty(Property.kt:84)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:96)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:96)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:17)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:22)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

example of xaml:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<ContentView x:Class="Symbiot.OtioCare.Mobile.Presentation.CustomViews.UserSectionView"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:Symbiot.OtioCare.Mobile.Presentation.CustomViews"
             xmlns:converters="clr-namespace:Symbiot.OtioCare.Mobile.Presentation.Converters;assembly=Symbiot.OtioCare.Mobile"
             xmlns:shades="http://sharpnado.com"
             x:Name="this"
             Margin="-10">
    <ContentView.Resources>
        <ResourceDictionary>
            <x:Double x:Key="BackgroundImageSize">294</x:Double>
            <x:Double x:Key="InnerOvalImageSize">330</x:Double>
            <x:Double x:Key="UserImageSize">160</x:Double>
        </ResourceDictionary>
    </ContentView.Resources>
    <Grid HorizontalOptions="Center"
          BindingContext="{x:Reference this}">
        <Image x:Name="OuterOvalImage"
               WidthRequest="{StaticResource BackgroundImageSize}"
               HeightRequest="{StaticResource BackgroundImageSize}"
               HorizontalOptions="Center"
               VerticalOptions="Center"
               Source="outer_oval.png" />

        <Image WidthRequest="{StaticResource InnerOvalImageSize}"
               HeightRequest="{StaticResource InnerOvalImageSize}"
               HorizontalOptions="Center"
               VerticalOptions="Center"
               Aspect="Fill"
               Source="inner_oval.png" />

        <Image x:Name="ProfileImage"
               WidthRequest="{Binding ImageSource,
                                      Converter={StaticResource HelpedUserImageUrlToHeightRequest}}"
               HeightRequest="{Binding ImageSource,
                                       Converter={StaticResource HelpedUserImageUrlToHeightRequest}}"
               HorizontalOptions="Center"
               VerticalOptions="Center"
               Aspect="AspectFill"
               IsVisible="{Binding ImageSource,
                                   Converter={converters:ValueToBoolConverter}}"
               Source="{Binding ImageSource}">
            <Image.Triggers>
                <DataTrigger Binding="{Binding Source={x:Reference ProfileImage},
                                               Path=HeightRequest}"
                             TargetType="Image"
                             Value="{StaticResource UserImageSize}">
                    <Setter Property="Clip">
                        <Setter.Value>
                            <EllipseGeometry Center="80,80"
                                             RadiusX="80"
                                             RadiusY="80" />
                        </Setter.Value>
                    </Setter>
                </DataTrigger>
            </Image.Triggers>
        </Image>

        <controls:SvgImageInCircle WidthRequest="{StaticResource UserImageSize}"
                                   HeightRequest="{StaticResource UserImageSize}"
                                   HorizontalOptions="Center"
                                   VerticalOptions="Center"
                                   BackgroundColor="{StaticResource very-light-purple-Two}"
                                   CornerRadius="80"
                                   IsVisible="{Binding ImageSource,
                                                       Converter={converters:IsNullConverter}}"
                                   SvgImageColor="{StaticResource ColorPrimary}"
                                   SvgImageSize="75"
                                   SvgImageSource="interface-essential-face-id.svg" />

        <shades:Shadows CornerRadius="25"
                        IsVisible="{Binding Source={x:Reference this},
                                            Path=HasEditButton}"
                        Shades="{StaticResource ShadowThinNeomorphism}">
            <controls:SvgImageInCircle Margin="0,0,75,83"
                                       HorizontalOptions="End"
                                       VerticalOptions="End"
                                       BackgroundColor="White"
                                       SvgImageColor="{StaticResource Purpley}"
                                       SvgImageSize="24"
                                       SvgImageSource="Symbiot.OtioCare.Mobile.Presentation.Svg.interface-essential-pen-edit.svg">
                <controls:SvgImageInCircle.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding BindingContext.EditPictureCommand, Source={x:Reference this}}" />
                </controls:SvgImageInCircle.GestureRecognizers>
            </controls:SvgImageInCircle>
        </shades:Shadows>
    </Grid>
</ContentView>
```

The xamlstyler file used:

[Settings.XamlStyler.txt](https://github.com/Xavalon/XamlStyler/files/6552710/Settings.XamlStyler.txt)

**Comment by roubachof** [comment]
I think it happens only when using an external config file...
Lately I have a really strange bug: when I save the files it toggles between my config file, and the xamlstyler config of the IDE.
So I think it could be related to conflict between the 2 configs.
