### ISSUE TITLE
Visual Studio 2017 RC not detected by new Installer

### ISSUE THREAD

**Issue by jstevenson72** [Xavalon/XamlStyler#84]
My Visual Studio 2017 RC is installed here:
**C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE**

![2017-01-11 10_17_39-new issue xavalon_xamlstyler](https://cloud.githubusercontent.com/assets/1573442/21856325/3c92891e-d7e7-11e6-9c41-f36f4503960e.png)

> 1/11/2017 10:12:18 AM - Microsoft VSIX Installer
1/11/2017 10:12:18 AM - -------------------------------------------
1/11/2017 10:12:18 AM - Initializing Install...
1/11/2017 10:12:18 AM - Extension Details...
1/11/2017 10:12:18 AM - 	Identifier         : a224be3c-88d1-4a57-9804-181dbef68021
1/11/2017 10:12:18 AM - 	Name               : XAML Styler 3
1/11/2017 10:12:18 AM - 	Author             : Xavalon
1/11/2017 10:12:18 AM - 	Version            : 3.0
1/11/2017 10:12:18 AM - 	Description        : XAML Styler is a visual studio extension, which formats XAML source code by sorting the attributes based on their importance. This tool can help you/your team maintain a better XAML coding style as well as a much better XAML readability.
1/11/2017 10:12:18 AM - 	Locale             : en-US
1/11/2017 10:12:18 AM - 	MoreInfoURL        : https://github.com/Xavalon/XamlStyler/
1/11/2017 10:12:18 AM - 	InstalledByMSI     : False
1/11/2017 10:12:18 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - 	SignatureState     : Unsigned
1/11/2017 10:12:18 AM - 	Supported Products : 
1/11/2017 10:12:18 AM - 		Microsoft.VisualStudio.Pro
1/11/2017 10:12:18 AM - 			Version : [15.0,16.0)
1/11/2017 10:12:18 AM - 		Microsoft.VisualStudio.Enterprise
1/11/2017 10:12:18 AM - 			Version : [15.0,16.0)
1/11/2017 10:12:18 AM - 		Microsoft.VisualStudio.Community
1/11/2017 10:12:18 AM - 			Version : [15.0,16.0)
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - 	References         : 
1/11/2017 10:12:18 AM - 		-------------------------------------------------------
1/11/2017 10:12:18 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
1/11/2017 10:12:18 AM - 		Name         : Visual Studio MPF 15.0
1/11/2017 10:12:18 AM - 		Version      : [15.0]
1/11/2017 10:12:18 AM - 		MoreInfoURL  : 
1/11/2017 10:12:18 AM - 		Nested       : No
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - Signature Details...
1/11/2017 10:12:18 AM - 	Extension is not signed.
1/11/2017 10:12:18 AM - 
1/11/2017 10:12:18 AM - Searching for applicable products...
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio Professional 2015
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio Community 2015
1/11/2017 10:12:18 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
1/11/2017 10:12:18 AM - Found installed product - Global Location
1/11/2017 10:12:18 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by jstevenson72** [comment]
This must me just my machine.  It appears as though no other extension are installing either.  I'll reinstall Visual Studio and hope for the best.  Thanks, sorry to waster your time.

**Comment by jstevenson72** [comment]
Reinstalling Visual Studio 2017 fixed the problem.
